### ISSUE TITLE
Issue with CPIS data

### ISSUE THREAD

**Issue by Fishland1** [pedrobtz/imf.data#11]
Hi, 

I tried loading the CPIS data, however, it keeps giving me an error and I'm not sure how. I was able to load other datasets such as DOTS. 

```r
library(imf.data)
CPIS <- load_datasets("CPIS")
result <- CPIS$get_series(freq = "A",
            ref_area = "US",
            indicator = "I_A_T_T_T_BP6_USD",
            counterpart_area = "W00",
            start_period = "2010-01-01",
            end_period = "2012-12-31")
``` 
This is the error: Error in FUN(X[[i]], ...) : "Obs" %in% names(x) is not TRUE

Thank you!

**Comment by pedrobtz** [comment]
Fixed with v0.1.7.
