### ISSUE TITLE
World Economic Outlook

### ISSUE THREAD

**Issue by Stefan2015-5** [pedrobtz/imf.data#8]
Hello, 
apologies if this is a dumb question but I am missing the World Economic Outlook in the data list: 

`imf_datasets <- list_datasets()

grep("World", ignore.case=T,imf_datasets$Description, value=T)
`

**Comment by pedrobtz** [comment]
@Stefan2015-5 the package is an interface to the IMF Data JSON API, the list of available datasets is here: https://data.imf.org/?sk=388dfa60-1d26-4ade-b505-a05a558d9a42&sid=1479329132316.
